### ISSUE TITLE
Remove dynamic Stats from pets table

### ISSUE THREAD

**Issue by leordev** [leordev/monstereos#1]
The contract should not have: `hunger`, `hp`, `awake`, `happiness`, `clean` stats. 

Instead we should have only the last timestamps of each relevant pet action and create a table where frontend apps can access "calc variables" like the `hunger_to_zero_interval`, `max_hunger_points` and then calculate it dynamically.

It would give real-time experience allowing UI to have full control to show beautiful bars and stats real-time.

**Comment by Velua** [comment]
Is this suggestion still inline with strategy?

**Comment by Velua** [comment]
Good points, another thought I had though is what if the app expands to greater logic link monster battles or stuff like that where things can dynamically change / events a front end client wouldn't be able to calculate so easily?

**Comment by Velua** [comment]
I suppose it all depends on the scope and the plan of it.

**Comment by friedger** [comment]
I disagree with the CONS:

* The frontend applications needs to know how to calculate the dynamic rules, otherwise the interface will reflect wrong status

The frontend can do whatever it wants with the data of the contract. It could display smartphones instead of monsters, could allow to charge them instead of feed, etc. Or do similar things interpreting the monsters as mathematical formulas that needs to be solved...

I think it is important for the game that the state can be calculated by the front end. (I was looking at my monsters and they seemed alive, when I fed them they died, because they were already dead some time ago.)

**Comment by leordev** [comment]
> The frontend can do whatever it wants with the data of the contract. It could display smartphones instead of monsters, could allow to charge them instead of feed, etc. Or do similar things interpreting the monsters as mathematical formulas that needs to be solved...

Loved your insight! Definitely agreed. At the end people will choose the best and fun interface/game they want to play, right?

> I think it is important for the game that the state can be calculated by the front end. (I was looking at my monsters and they seemed alive, when I fed them they died, because they were already dead some time ago.)

It's something that I'm messing around with recursive defer transactions. Just testing to see if it's a good approach, when it's working the frontend get's data almost like "real-time" (this is a con of having the status in the contract instead of only calc formulas), but when the recursion is broken for some reason that I could not identify the pet status stays outdated and you only discover the real one when you submit an action (because we always update the pet status before). 

Check this out:

```
   // recursive infinite update if not dead, each minute
    uint32_t new_iteration = iteration + 1;
    uint64_t new_trx_id = (pet_id << 32 | new_iteration);
    transaction update{};
    update.actions.emplace_back(
        permission_level{_self, N(active)},
        _self, N(updatepet),
        std::make_tuple(pet_id, new_iteration)
    );
    update.delay_sec = 60;
    update.send(new_trx_id, _self);
```

The above code is called from the `updatepet` action itself, in the end, causing a recursive loop of deferred transactions: https://github.com/leordev/monstereos/blob/master/contracts/pet/pet.cpp#L76-L86

PS: @bytemaster @tbfleming @heifner - I know you guys are super busy but would love to have any insights from you about having recursive deferred transactions. Is it a good idea to have it? For me it does not look like for now... It sounds more reasonable and controllable to create a backend oracle to always monitor/watch and submits a transaction whenever needed.

**Comment by friedger** [comment]
I don't think that it is necessary to update the state of the game every minute, why not every 10 minutes or every second.

Maybe you want to publish an update/verifyState action that allows to update the state. The backend would just keep the relevant transactions with time stamps. The front end can estimate the actual state and if they want call the verifyState action to see whether the estimation was correct. Thereby, the backend would only calculate the state when needed.

**Comment by tbfleming** [comment]
I was about to answer your question when I noticed something: it could get expensive since you'd need to do it for each pet.

Chances are high that at least some of your deferred transactions will hit hard failures and stop.

**Comment by tbfleming** [comment]
hard failure: deferred transaction fails and notifying your contract of the failure also fails.

**Comment by leordev** [comment]
got it. so I can assume it's better to have an oracle taking care and handling whatever I need to watch in my contracts and submitting updates if ever needed!

**Comment by leordev** [comment]
already changed the contracts to dynamic attributes only, serving the calcs params in a singleton table
