### ISSUE TITLE
get_table_rows http500

### ISSUE THREAD

**Issue by t-bast** [leordev/monstereos#15]
Hey guys,

I wanted to try the MonsterEOS on the jungle testnet, but since yesterday it has only been returning http 500 on get_table_rows calls so I can't even create my first monster.
Are you aware of the issue? Is there something I can do to help debug? I can provide network traces if you're unable to repro.

Cheers,

**Comment by Velua** [comment]
Have you tried using the version on the main net at [MonsterEOS.io](http://monstereos.io) ?

**Comment by t-bast** [comment]
Makes sense then ;)
It's surprising that the API is returning HTTP 500 (I'd expect a 4xx code) but I can definitely live with that.
Thanks for the quick response!

**Comment by leordev** [comment]
Sorry for that, actually I’m creating an issue to improve error handling… we have a bunch that could be explained.
