### ISSUE TITLE
Please allow user to delete pet

### ISSUE THREAD

**Issue by alienzin** [leordev/monstereos#17]
When a new user create a pet in pet::createpet(), the data get emplaced on user's RAM since the payer is user.
But there's no way to erase the data.

So please let user to delete his/her pets.
And i suggest you to notice user that the pet data occupies user's RAM (bytes / pet).

Thank you for good EOS dApp experience.

**Comment by friedger** [comment]
I think this is in work. We also added the information about RAM into the ricardian contract.

**Comment by Velua** [comment]
Thanks @alienzin I totally agree, we've already got this one in development. Leo is on it!

**Comment by leordev** [comment]
already did a while ago, somehow I forgot to close it

**Comment by alienzin** [comment]
@leordev thank you for your effort.
