### ISSUE TITLE
monster PVP system

### ISSUE THREAD

**Issue by destinysaid** [leordev/monstereos#32]
a way for users to interact with their monsters, other than feeding, petting or even washing would be a very nice addition to the experiment.

Sort of like if you've played pokemon, or bakugan or digimon or any of the infinite systems that are out there.

A workable system like this would be amazing @leordev

**Comment by leordev** [comment]
here you go buddy:
![image](https://user-images.githubusercontent.com/6147142/42036700-4997572c-7ab4-11e8-8476-8769d04b439b.png)
