### ISSUE TITLE
Add classification, skills and points to the monsters

### ISSUE THREAD

**Issue by destinysaid** [leordev/monstereos#36]
The monsters are mostly categorized into about 8-10 different designs from what I've seen so far, the monsters can be given specific classifications such as 

Dark- for the skeletons and ghouls
Nature- For the shrooms and plants
magic- For the shaman and others

Just find a good set of classifications.

Skills according to their classification, slight weakness against a certain type of monster ad strength against others.

**Comment by leordev** [comment]
We have elements for now, it's all dynamic so we can add/remove elements and change elements for what makes sense for each monster check this #42
