### ISSUE TITLE
How do you prevent people from calling the "transfer" action directly without going through eosio.token?

### ISSUE THREAD

**Issue by mochunhei** [leordev/monstereos#37]
Sorry if I am wrong, I am still learning.
In pet.cpp:
```
void pet::transfer(uint64_t sender, uint64_t receiver) {
    print("\n>>> sender >>>", sender, " - name: ", name{sender});
    print("\n>>> receiver >>>", receiver, " - name: ", name{receiver});

    // ??? Don't need to verify because we already did it in EOSIO_ABI_EX ???
    // eosio_assert(code == N(eosio.token), "I reject your non-eosio.token deposit");

    // ...
```
You commented out the eosio_assert() saying don't need to verify. However this transfer() is a public function meaning people can call it directly. How do you prevent such a case without checking the source of action?

**Comment by leordev** [comment]
https://github.com/leordev/monstereos/blob/master/contracts/pet/pet.cpp#L279

**Comment by mochunhei** [comment]
That's an "OR" condition, that means people can send the "transfer" action directly to "monstereosio" instead of "eosio.token" and still arrive the same function.
