### ISSUE TITLE
can't continue the game

### ISSUE THREAD

**Issue by jjnetcn** [leordev/monstereos#38]
i create a monster and it sleeping.
i  create the battle, so no pet to choose to continue fight.
in main page http://monstereos.io/ tips i'am join the battle and can't return
another page, so i can't do anything.. maybe should cancel the battle or to wake my pet or create
another pet or other things.

**Comment by leordev** [comment]
just finished your battle through admin account in the smart contract, sorry by that. I already created a lock that only allow people with available monsters to create/join battles
