### ISSUE TITLE
stuck in Picking Phase if opponent not selecting a monster

### ISSUE THREAD

**Issue by Danwaji** [leordev/monstereos#39]
after we confirmed that we are ready to fight, my opponent can't picking his monster (because he only had one, which was asleep).
The screeen says: "Now Picking Phase: Waiting for Player *Opponentname* pick"
there is no option to leave the fight, what makes both of us stuck in this battle for eternity, because he cant wake up his monster since he is stuck as well

**Comment by jjnetcn** [comment]
。。。。 it's me

**Comment by leordev** [comment]
I added a lock that verifies if you have any enabled monster before joining or creating a battle
