### ISSUE TITLE
continuos network error on app (see image)

### ISSUE THREAD

**Issue by rreeve** [leordev/monstereos#45]
Whenever I load the webpage I get a continous stream of red blocks that say monster fail. See image.

![monstereos](https://user-images.githubusercontent.com/8009013/42053264-00a311c8-7b09-11e8-9507-3b9ae498a6af.JPG)

**Comment by leordev** [comment]
can you please do a right click on your screen, click inspect, go to the network tab, press esc to also show the console in the bottom half of the screen and print what's there? try to get the last errors

**Comment by rreeve** [comment]
Hi,
I hope this is right, if not let me know what i'm doing wrong.

![error](https://user-images.githubusercontent.com/8009013/42061989-fb013798-7b23-11e8-8a87-b1ff525a8095.JPG)

**Comment by felipemartim** [comment]
Same thing here. My screenshot:
<img width="1385" alt="screenshot 2018-06-29 00 29 06" src="https://user-images.githubusercontent.com/570829/42071780-7d67f794-7b33-11e8-835c-6a75efa9ce02.png">

**Comment by felipemartim** [comment]
I can also see these error messages:

Mixed Content: The page at 'https://monstereos.io/' was loaded over HTTPS, but requested an insecure resource 'http://mainnet.eoscalgary.io/v1/chain/get_info'. This request has been blocked; the content must be served over HTTPS.

Mixed Content: The page at 'https://monstereos.io/' was loaded over HTTPS, but requested an insecure resource 'http://mainnet.eoscalgary.io/v1/chain/get_table_rows'. This request has been blocked; the content must be served over HTTPS.

**Comment by leordev** [comment]
@felipemartim nice debug my friend!!! Try to access http://monstereos.io instead of httpS://monstereos.io

we are not supporting https for now, but you guys are safe because everything is signed in your local Scatter. https/http does not matter. Can you let me know if it also works for you @rreeve

**Comment by felipemartim** [comment]
@leordev thanks, http works but Google redirects to https automatically.

**Comment by rreeve** [comment]
@leordev Yes, it works perfectly now. Thanks.
