### ISSUE TITLE
If number of pets reach 5000  and I add new one

### ISSUE THREAD

**Issue by bachvtuan** [leordev/monstereos#46]
![screenshot from 2018-06-29 14-14-12](https://user-images.githubusercontent.com/2065400/42078564-332120ec-7ba7-11e8-839e-f73555123d8c.png)

I just inspect your code and I see you limit 5000 pet items when query table pets.
I wonder if this table reach this number and I add new one .
Am I able to see my pet ?
I think for now simply just increase limit number but for future usage if we reach 1 millions.
what's your solution ?

**Comment by leordev** [comment]
polling is horrible! I think we already reached the limit that we could without a nice backend to support our operations. the solution is described here: #40
