### ISSUE TITLE
RAM to create a new monster

### ISSUE THREAD

**Issue by felipemartim** [leordev/monstereos#49]
In the Ricardian Contract, it is said that the user must pay for 295KB of RAM used by the monster. The cost of this ammount of RAM seems to be 33 EOS as of today prices.

Why do we need so much RAM?

**Comment by leordev** [comment]
this amount is incorrect. it's 295 bytes, 0.3kb, we already pushed to master branch this adjustment, we just need to deploy it in the mainnet
