### ISSUE TITLE
Stuck in battle arena

### ISSUE THREAD

**Issue by hydrosloth** [leordev/monstereos#52]
So i entered a battle arena,  and the option to leave battle has disappeared..    Ive been stuck in the arena with no way to get out.     Its hard to feed my monsters because i am automatically brought to the battle arena when i goto monstereos

**Comment by hydrosloth** [comment]
still stuck..   been almost a week now

**Comment by leordev** [comment]
Already released the stuck battles. Sorry for being out. I’m through hectic days :/
