### ISSUE TITLE
Jungle nestnet update (

### ISSUE THREAD

**Issue by igavva** [leordev/monstereos#7]
My monsters is dead (
Please update chainId to 038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca

**Comment by leordev** [comment]
I'm sorry to hear that... As soon as I get a break I will update to the new chain!

**Comment by leordev** [comment]
@igavva we just released in mainnet! I'm touching base with folks from junglenet and we are going to probably open an "Animals Jungle" themed game over there so we can test the big changes before ever deploying and breaking stuff in the official released version of mainnet!
