### ISSUE TITLE
What is required to run on mainnet?

### ISSUE THREAD

**Issue by kirkins** [leordev/monstereos#8]
I installed elm and am running on localhost.

I remember you saying the contract won't be live on mainnet. I'm wondering what is required?

The contract needs to have EOS staked? Or users supply the RAM to make transactions?

Completely new to EOS development but interested in trying this.

**Comment by leordev** [comment]
Hi @kirkins , I'm glad you installed it in your own machine and were able to run it! 😄 (I didn't have time to write good installation steps).

So you can deploy in the mainnet when it launches you just need to stake an account. Well the code right now requires 1 EOS for pet creation, you could use that to stake more RAM and allow more users. But I'm not sure how sustainable it is. I didn't have a chance to take this project serious but feel free if you want to!

Thank you for your interest, I will be glad to help you 💪

**Comment by leordev** [comment]
@kirkins we just released my friend! Check it out at monstereos.io ! Go EOS Go!

**Comment by kirkins** [comment]
Nice this is awesome!
